### ISSUE TITLE
[Project] User advisory board revitalization

### ISSUE THREAD

**Issue by babaklar** [MESH-Research/hc-community#121]
## Description ##
This project re-examines the role of our user advisory board in the governing structure of the Commons and moves away from a formal structure to a more open "user champion" program. The goals of this project are:
- Engage users in the work of the Commons
- Make more solid connections between the Commons team and our users
- Create a group of Commons advocates

Assessment of the success of this project will be: 
- Number of users who sign up
- Number of users who "participate"
- Other items?

## Deliverables ##
Deliverables for this project will include the following:
- [ ] 1 blog post introducing the program to our users, and additional posts with group updates as needed
- [ ] Social media campaign to inform users of the program
- [ ] Quarterly (?) newsletters specifically for these users
- [ ] Quarterly meet up on Zoom
- [ ] Swag to share out with the initial cohort (stickers, personalized note, etc.) 
- [ ] Commons site or page on growing

## To Do ##

**Phase One - Planning**
- [ ] Collaborate with the community team on goals for the champions program and decision making on what perks should be
- [ ] Follow up with dev team on any aspects that need dev input (for example, badges and site perks)
- [ ] Choose date for full launch of campaign
- [ ] Choose dates for 2023-2024 meetings

**Phase Two - Contacting current board members**
- [ ] Create Qualtrics opt in/out for current user advisory group members
- [ ] Email current members about end of term/changes to structure moving forward

**Phase Three - Designing/creating deliverables**
- [ ] Write a blog post with full details of what champions are, what the perks are, and how to get involved
- [ ] Develop social media campaign to promo the champions nomination process
- [ ] Create a nomination form in Qualtrics for users to self nominate

**Phase Four - Campaign Launch**
- [ ] Release all of the relevant info publicly

**Phase Five - Kickoff meeting**
- [ ] Plan for kickoff meeting

## Target Timeline ##
- [ ] Phase One - June-July 2023
- [ ] Phase Two - July 2023
- [ ] Phase Three - August September 2023
- [ ] Phase Four - October 2023
- [ ] Phase Five - November 2023

## Responsibilities ##
**Community Lead (Accountable)**: Larissa
**Development Lead (Responsible)**: MT (where needed)
**Responsible**:
**Consulted**: 
**Informed**:

## Additional Documentation ##
[https://docs.google.com/document/d/1C2oLpoDpvu50NWVLPFWbYyLoWZlvY2zvwKWuQxBRts8/edit](https://docs.google.com/document/d/1C2oLpoDpvu50NWVLPFWbYyLoWZlvY2zvwKWuQxBRts8/edit)
[https://miro.com/welcomeonboard/a0laRGFza3V6M3VGQVpOTENkSVg4cmtnZTdrTXdUbFppU2Y0S2JWa09lQ2VRakRWVFBrNWNrTUNwd0NTN3ZnWHwzNDU4NzY0NTIzMDM5OTM4OTU5fDI=?share_link_id=646132121614](https://miro.com/welcomeonboard/a0laRGFza3V6M3VGQVpOTENkSVg4cmtnZTdrTXdUbFppU2Y0S2JWa09lQ2VRakRWVFBrNWNrTUNwd0NTN3ZnWHwzNDU4NzY0NTIzMDM5OTM4OTU5fDI=?share_link_id=646132121614)
