### ISSUE TITLE
[Project] Metrics and Matomo

### ISSUE THREAD

**Issue by bjr70** [MESH-Research/hc-community#137]
## Description ##

Re-evaluate the metrics we're tracking across WordPress and Google Analytics, and evaluate moving to Matomo Analytics. 

**Steps for evaluating Matomo:**
- We identify a technical team member to co-lead this project with the community team
- We plan and execute a three month pilot of the base plan on the Commons
- Choose an upcoming event to run an additional month long (free trial) concurrent pilot of the paid features to determine the fit for the platform

[Matomo Business Case document](https://docs.google.com/document/d/1ZFGNkzBImXGkmAifgXQwnVX8Cat_tB_877Fl4v-67UI/edit?usp=sharing)
**Planning/Design document**: *Link to more detailed document, if one exists*

## Deliverables ##

- A fully documented set of metrics to be collected and reported on
- A decision on the metrics platform we'll use moving forward (GA or Matomo)

##To Do##

- [ ] [Community Development of Metrics Questions - hc-community-52](https://app.zenhub.com/workspaces/hc-communityux-6373ff768e755e001c4424d0/issues/gh/mesh-research/hc-community/52
- [ ] [Establish User Activity Metrics - hc-community#53](https://app.zenhub.com/workspaces/hc-communityux-6373ff768e755e001c4424d0/issues/gh/mesh-research/hc-community/53)
- [ ] [Test/Implement New Metrics Platform - hc-community#55](https://app.zenhub.com/workspaces/hc-communityux-6373ff768e755e001c4424d0/issues/gh/mesh-research/hc-community/55)
- [ ] [Produce Analytic Reports - hc-community#56](https://app.zenhub.com/workspaces/hc-communityux-6373ff768e755e001c4424d0/issues/gh/mesh-research/hc-community/56)
)

##Development Tickets##

- [ ] [Switch from GA / Matomo Pilot - commons#542](https://app.zenhub.com/workspaces/hc-development-61143609f268f000196abf18/issues/gh/mesh-research/commons/542)
- [ ] [Explore Google Analytics Options/Data Flows/Data Viz - humanities-commons#53](https://app.zenhub.com/workspaces/hc-development-61143609f268f000196abf18/issues/gh/mesh-research/humanities-commons/53)
- [ ] [Initial Metrics for HASTAC - HASTAC-Migration#91](https://app.zenhub.com/workspaces/hc-development-61143609f268f000196abf18/issues/gh/mesh-research/hastac-migration/91)

## Target Timeline ##

- [ ] Planning complete: MM-DD
- [ ] Milestone 1: MM-DD
- [ ] Milestone 2: MM-DD
- [ ] Milestone 3: MM-DD
- [ ] Project complete: MM-DD

## Responsibilities ##

**Community Lead**: 
**Development Lead Dimitris**:
**Responsible**:
**Consulted**:
**Informed**:
