### ISSUE TITLE
[Project] Mailchimp implementation

### ISSUE THREAD

**Issue by bjr70** [MESH-Research/hc-community#138]
## Description ##

Move newsletters and user communication from Stripo and developer intervention to the Mailchimp platform. This will coordinate with the definition and identification of "active" users of the platform. 

**Planning/Design document**: *Link to more detailed document, if one exists*

## Deliverables ##

- *List of specific components that will be delivered by the project.*

##To Do##

- [ ] Create synchronized MailChimp email list - hc-support#498 
- [ ] [Make plan to email users to switch to MC newsletter - hc-community#127](https://app.zenhub.com/workspaces/hc-communityux-6373ff768e755e001c4424d0/issues/gh/mesh-research/hc-community/127)
- [ ] [Figure out active/inactive user definition hc-community#116](https://app.zenhub.com/workspaces/hc-communityux-6373ff768e755e001c4424d0/issues/gh/mesh-research/hc-community/116)

## Target Timeline ##

- [ ] Planning complete: MM-DD
- [ ] Milestone 1: MM-DD
- [ ] Milestone 2: MM-DD
- [ ] Milestone 3: MM-DD
- [ ] Project complete: MM-DD

## Responsibilities ##

**Community Lead (Accountable)**: 
**Development Lead (Responsible)**:
**Responsible**:
**Consulted**:
**Informed**:
